/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokensTypographyRouteImport } from './routes/tokens/typography'
import { Route as TokensSpacingRouteImport } from './routes/tokens/spacing'
import { Route as TokensMiscRouteImport } from './routes/tokens/misc'
import { Route as TokensColorsRouteImport } from './routes/tokens/colors'
import { Route as GettingStartedUsageRouteImport } from './routes/getting-started/usage'
import { Route as GettingStartedInstallationRouteImport } from './routes/getting-started/installation'
import { Route as GettingStartedCustomizationRouteImport } from './routes/getting-started/customization'
import { Route as ComponentsTypographyRouteImport } from './routes/components/typography'
import { Route as ComponentsTooltipRouteImport } from './routes/components/tooltip'
import { Route as ComponentsTextFieldRouteImport } from './routes/components/text-field'
import { Route as ComponentsTabsRouteImport } from './routes/components/tabs'
import { Route as ComponentsTableRouteImport } from './routes/components/table'
import { Route as ComponentsSwitchRouteImport } from './routes/components/switch'
import { Route as ComponentsStackRouteImport } from './routes/components/stack'
import { Route as ComponentsSnackbarRouteImport } from './routes/components/snackbar'
import { Route as ComponentsSliderRouteImport } from './routes/components/slider'
import { Route as ComponentsSkeletonRouteImport } from './routes/components/skeleton'
import { Route as ComponentsSidebarComponentRouteImport } from './routes/components/sidebar-component'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsSearchBarRouteImport } from './routes/components/search-bar'
import { Route as ComponentsRadioRouteImport } from './routes/components/radio'
import { Route as ComponentsPaginationRouteImport } from './routes/components/pagination'
import { Route as ComponentsNavbarComponentRouteImport } from './routes/components/navbar-component'
import { Route as ComponentsMenuRouteImport } from './routes/components/menu'
import { Route as ComponentsListRouteImport } from './routes/components/list'
import { Route as ComponentsLinearProgressRouteImport } from './routes/components/linear-progress'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsIconRouteImport } from './routes/components/icon'
import { Route as ComponentsFormFieldRouteImport } from './routes/components/form-field'
import { Route as ComponentsDrawerRouteImport } from './routes/components/drawer'
import { Route as ComponentsDividerRouteImport } from './routes/components/divider'
import { Route as ComponentsDialogRouteImport } from './routes/components/dialog'
import { Route as ComponentsDatePickerRouteImport } from './routes/components/date-picker'
import { Route as ComponentsDataTableRouteImport } from './routes/components/data-table'
import { Route as ComponentsCircularProgressRouteImport } from './routes/components/circular-progress'
import { Route as ComponentsChipRouteImport } from './routes/components/chip'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsCardRouteImport } from './routes/components/card'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsBreadcrumbsRouteImport } from './routes/components/breadcrumbs'
import { Route as ComponentsBoxRouteImport } from './routes/components/box'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'
import { Route as ComponentsAvatarRouteImport } from './routes/components/avatar'
import { Route as ComponentsAutocompleteRouteImport } from './routes/components/autocomplete'
import { Route as ComponentsAlertRouteImport } from './routes/components/alert'
import { Route as ComponentsAccordionRouteImport } from './routes/components/accordion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensTypographyRoute = TokensTypographyRouteImport.update({
  id: '/tokens/typography',
  path: '/tokens/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensSpacingRoute = TokensSpacingRouteImport.update({
  id: '/tokens/spacing',
  path: '/tokens/spacing',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensMiscRoute = TokensMiscRouteImport.update({
  id: '/tokens/misc',
  path: '/tokens/misc',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensColorsRoute = TokensColorsRouteImport.update({
  id: '/tokens/colors',
  path: '/tokens/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedUsageRoute = GettingStartedUsageRouteImport.update({
  id: '/getting-started/usage',
  path: '/getting-started/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedInstallationRoute =
  GettingStartedInstallationRouteImport.update({
    id: '/getting-started/installation',
    path: '/getting-started/installation',
    getParentRoute: () => rootRouteImport,
  } as any)
const GettingStartedCustomizationRoute =
  GettingStartedCustomizationRouteImport.update({
    id: '/getting-started/customization',
    path: '/getting-started/customization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsTypographyRoute = ComponentsTypographyRouteImport.update({
  id: '/components/typography',
  path: '/components/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/components/tooltip',
  path: '/components/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextFieldRoute = ComponentsTextFieldRouteImport.update({
  id: '/components/text-field',
  path: '/components/text-field',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTabsRoute = ComponentsTabsRouteImport.update({
  id: '/components/tabs',
  path: '/components/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTableRoute = ComponentsTableRouteImport.update({
  id: '/components/table',
  path: '/components/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/components/switch',
  path: '/components/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsStackRoute = ComponentsStackRouteImport.update({
  id: '/components/stack',
  path: '/components/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSnackbarRoute = ComponentsSnackbarRouteImport.update({
  id: '/components/snackbar',
  path: '/components/snackbar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSliderRoute = ComponentsSliderRouteImport.update({
  id: '/components/slider',
  path: '/components/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSkeletonRoute = ComponentsSkeletonRouteImport.update({
  id: '/components/skeleton',
  path: '/components/skeleton',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSidebarComponentRoute =
  ComponentsSidebarComponentRouteImport.update({
    id: '/components/sidebar-component',
    path: '/components/sidebar-component',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSearchBarRoute = ComponentsSearchBarRouteImport.update({
  id: '/components/search-bar',
  path: '/components/search-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRadioRoute = ComponentsRadioRouteImport.update({
  id: '/components/radio',
  path: '/components/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPaginationRoute = ComponentsPaginationRouteImport.update({
  id: '/components/pagination',
  path: '/components/pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNavbarComponentRoute =
  ComponentsNavbarComponentRouteImport.update({
    id: '/components/navbar-component',
    path: '/components/navbar-component',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsMenuRoute = ComponentsMenuRouteImport.update({
  id: '/components/menu',
  path: '/components/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsListRoute = ComponentsListRouteImport.update({
  id: '/components/list',
  path: '/components/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsLinearProgressRoute =
  ComponentsLinearProgressRouteImport.update({
    id: '/components/linear-progress',
    path: '/components/linear-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/components/input',
  path: '/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIconRoute = ComponentsIconRouteImport.update({
  id: '/components/icon',
  path: '/components/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormFieldRoute = ComponentsFormFieldRouteImport.update({
  id: '/components/form-field',
  path: '/components/form-field',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDrawerRoute = ComponentsDrawerRouteImport.update({
  id: '/components/drawer',
  path: '/components/drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDividerRoute = ComponentsDividerRouteImport.update({
  id: '/components/divider',
  path: '/components/divider',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDialogRoute = ComponentsDialogRouteImport.update({
  id: '/components/dialog',
  path: '/components/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDatePickerRoute = ComponentsDatePickerRouteImport.update({
  id: '/components/date-picker',
  path: '/components/date-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDataTableRoute = ComponentsDataTableRouteImport.update({
  id: '/components/data-table',
  path: '/components/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCircularProgressRoute =
  ComponentsCircularProgressRouteImport.update({
    id: '/components/circular-progress',
    path: '/components/circular-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsChipRoute = ComponentsChipRouteImport.update({
  id: '/components/chip',
  path: '/components/chip',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCardRoute = ComponentsCardRouteImport.update({
  id: '/components/card',
  path: '/components/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBreadcrumbsRoute = ComponentsBreadcrumbsRouteImport.update({
  id: '/components/breadcrumbs',
  path: '/components/breadcrumbs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBoxRoute = ComponentsBoxRouteImport.update({
  id: '/components/box',
  path: '/components/box',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAvatarRoute = ComponentsAvatarRouteImport.update({
  id: '/components/avatar',
  path: '/components/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAutocompleteRoute = ComponentsAutocompleteRouteImport.update({
  id: '/components/autocomplete',
  path: '/components/autocomplete',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAlertRoute = ComponentsAlertRouteImport.update({
  id: '/components/alert',
  path: '/components/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAccordionRoute = ComponentsAccordionRouteImport.update({
  id: '/components/accordion',
  path: '/components/accordion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/autocomplete': typeof ComponentsAutocompleteRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/box': typeof ComponentsBoxRoute
  '/components/breadcrumbs': typeof ComponentsBreadcrumbsRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/chip': typeof ComponentsChipRoute
  '/components/circular-progress': typeof ComponentsCircularProgressRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/divider': typeof ComponentsDividerRoute
  '/components/drawer': typeof ComponentsDrawerRoute
  '/components/form-field': typeof ComponentsFormFieldRoute
  '/components/icon': typeof ComponentsIconRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/linear-progress': typeof ComponentsLinearProgressRoute
  '/components/list': typeof ComponentsListRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/navbar-component': typeof ComponentsNavbarComponentRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/radio': typeof ComponentsRadioRoute
  '/components/search-bar': typeof ComponentsSearchBarRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar-component': typeof ComponentsSidebarComponentRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/snackbar': typeof ComponentsSnackbarRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/text-field': typeof ComponentsTextFieldRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/typography': typeof ComponentsTypographyRoute
  '/getting-started/customization': typeof GettingStartedCustomizationRoute
  '/getting-started/installation': typeof GettingStartedInstallationRoute
  '/getting-started/usage': typeof GettingStartedUsageRoute
  '/tokens/colors': typeof TokensColorsRoute
  '/tokens/misc': typeof TokensMiscRoute
  '/tokens/spacing': typeof TokensSpacingRoute
  '/tokens/typography': typeof TokensTypographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/autocomplete': typeof ComponentsAutocompleteRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/box': typeof ComponentsBoxRoute
  '/components/breadcrumbs': typeof ComponentsBreadcrumbsRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/chip': typeof ComponentsChipRoute
  '/components/circular-progress': typeof ComponentsCircularProgressRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/divider': typeof ComponentsDividerRoute
  '/components/drawer': typeof ComponentsDrawerRoute
  '/components/form-field': typeof ComponentsFormFieldRoute
  '/components/icon': typeof ComponentsIconRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/linear-progress': typeof ComponentsLinearProgressRoute
  '/components/list': typeof ComponentsListRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/navbar-component': typeof ComponentsNavbarComponentRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/radio': typeof ComponentsRadioRoute
  '/components/search-bar': typeof ComponentsSearchBarRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar-component': typeof ComponentsSidebarComponentRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/snackbar': typeof ComponentsSnackbarRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/text-field': typeof ComponentsTextFieldRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/typography': typeof ComponentsTypographyRoute
  '/getting-started/customization': typeof GettingStartedCustomizationRoute
  '/getting-started/installation': typeof GettingStartedInstallationRoute
  '/getting-started/usage': typeof GettingStartedUsageRoute
  '/tokens/colors': typeof TokensColorsRoute
  '/tokens/misc': typeof TokensMiscRoute
  '/tokens/spacing': typeof TokensSpacingRoute
  '/tokens/typography': typeof TokensTypographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/autocomplete': typeof ComponentsAutocompleteRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/box': typeof ComponentsBoxRoute
  '/components/breadcrumbs': typeof ComponentsBreadcrumbsRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/chip': typeof ComponentsChipRoute
  '/components/circular-progress': typeof ComponentsCircularProgressRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/divider': typeof ComponentsDividerRoute
  '/components/drawer': typeof ComponentsDrawerRoute
  '/components/form-field': typeof ComponentsFormFieldRoute
  '/components/icon': typeof ComponentsIconRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/linear-progress': typeof ComponentsLinearProgressRoute
  '/components/list': typeof ComponentsListRoute
  '/components/menu': typeof ComponentsMenuRoute
  '/components/navbar-component': typeof ComponentsNavbarComponentRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/radio': typeof ComponentsRadioRoute
  '/components/search-bar': typeof ComponentsSearchBarRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar-component': typeof ComponentsSidebarComponentRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/snackbar': typeof ComponentsSnackbarRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/text-field': typeof ComponentsTextFieldRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/typography': typeof ComponentsTypographyRoute
  '/getting-started/customization': typeof GettingStartedCustomizationRoute
  '/getting-started/installation': typeof GettingStartedInstallationRoute
  '/getting-started/usage': typeof GettingStartedUsageRoute
  '/tokens/colors': typeof TokensColorsRoute
  '/tokens/misc': typeof TokensMiscRoute
  '/tokens/spacing': typeof TokensSpacingRoute
  '/tokens/typography': typeof TokensTypographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components/accordion'
    | '/components/alert'
    | '/components/autocomplete'
    | '/components/avatar'
    | '/components/badge'
    | '/components/box'
    | '/components/breadcrumbs'
    | '/components/button'
    | '/components/card'
    | '/components/checkbox'
    | '/components/chip'
    | '/components/circular-progress'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/divider'
    | '/components/drawer'
    | '/components/form-field'
    | '/components/icon'
    | '/components/input'
    | '/components/linear-progress'
    | '/components/list'
    | '/components/menu'
    | '/components/navbar-component'
    | '/components/pagination'
    | '/components/radio'
    | '/components/search-bar'
    | '/components/select'
    | '/components/sidebar-component'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/snackbar'
    | '/components/stack'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/text-field'
    | '/components/tooltip'
    | '/components/typography'
    | '/getting-started/customization'
    | '/getting-started/installation'
    | '/getting-started/usage'
    | '/tokens/colors'
    | '/tokens/misc'
    | '/tokens/spacing'
    | '/tokens/typography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/accordion'
    | '/components/alert'
    | '/components/autocomplete'
    | '/components/avatar'
    | '/components/badge'
    | '/components/box'
    | '/components/breadcrumbs'
    | '/components/button'
    | '/components/card'
    | '/components/checkbox'
    | '/components/chip'
    | '/components/circular-progress'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/divider'
    | '/components/drawer'
    | '/components/form-field'
    | '/components/icon'
    | '/components/input'
    | '/components/linear-progress'
    | '/components/list'
    | '/components/menu'
    | '/components/navbar-component'
    | '/components/pagination'
    | '/components/radio'
    | '/components/search-bar'
    | '/components/select'
    | '/components/sidebar-component'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/snackbar'
    | '/components/stack'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/text-field'
    | '/components/tooltip'
    | '/components/typography'
    | '/getting-started/customization'
    | '/getting-started/installation'
    | '/getting-started/usage'
    | '/tokens/colors'
    | '/tokens/misc'
    | '/tokens/spacing'
    | '/tokens/typography'
  id:
    | '__root__'
    | '/'
    | '/components/accordion'
    | '/components/alert'
    | '/components/autocomplete'
    | '/components/avatar'
    | '/components/badge'
    | '/components/box'
    | '/components/breadcrumbs'
    | '/components/button'
    | '/components/card'
    | '/components/checkbox'
    | '/components/chip'
    | '/components/circular-progress'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/divider'
    | '/components/drawer'
    | '/components/form-field'
    | '/components/icon'
    | '/components/input'
    | '/components/linear-progress'
    | '/components/list'
    | '/components/menu'
    | '/components/navbar-component'
    | '/components/pagination'
    | '/components/radio'
    | '/components/search-bar'
    | '/components/select'
    | '/components/sidebar-component'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/snackbar'
    | '/components/stack'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/text-field'
    | '/components/tooltip'
    | '/components/typography'
    | '/getting-started/customization'
    | '/getting-started/installation'
    | '/getting-started/usage'
    | '/tokens/colors'
    | '/tokens/misc'
    | '/tokens/spacing'
    | '/tokens/typography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsAccordionRoute: typeof ComponentsAccordionRoute
  ComponentsAlertRoute: typeof ComponentsAlertRoute
  ComponentsAutocompleteRoute: typeof ComponentsAutocompleteRoute
  ComponentsAvatarRoute: typeof ComponentsAvatarRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsBoxRoute: typeof ComponentsBoxRoute
  ComponentsBreadcrumbsRoute: typeof ComponentsBreadcrumbsRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCardRoute: typeof ComponentsCardRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsChipRoute: typeof ComponentsChipRoute
  ComponentsCircularProgressRoute: typeof ComponentsCircularProgressRoute
  ComponentsDataTableRoute: typeof ComponentsDataTableRoute
  ComponentsDatePickerRoute: typeof ComponentsDatePickerRoute
  ComponentsDialogRoute: typeof ComponentsDialogRoute
  ComponentsDividerRoute: typeof ComponentsDividerRoute
  ComponentsDrawerRoute: typeof ComponentsDrawerRoute
  ComponentsFormFieldRoute: typeof ComponentsFormFieldRoute
  ComponentsIconRoute: typeof ComponentsIconRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsLinearProgressRoute: typeof ComponentsLinearProgressRoute
  ComponentsListRoute: typeof ComponentsListRoute
  ComponentsMenuRoute: typeof ComponentsMenuRoute
  ComponentsNavbarComponentRoute: typeof ComponentsNavbarComponentRoute
  ComponentsPaginationRoute: typeof ComponentsPaginationRoute
  ComponentsRadioRoute: typeof ComponentsRadioRoute
  ComponentsSearchBarRoute: typeof ComponentsSearchBarRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSidebarComponentRoute: typeof ComponentsSidebarComponentRoute
  ComponentsSkeletonRoute: typeof ComponentsSkeletonRoute
  ComponentsSliderRoute: typeof ComponentsSliderRoute
  ComponentsSnackbarRoute: typeof ComponentsSnackbarRoute
  ComponentsStackRoute: typeof ComponentsStackRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTableRoute: typeof ComponentsTableRoute
  ComponentsTabsRoute: typeof ComponentsTabsRoute
  ComponentsTextFieldRoute: typeof ComponentsTextFieldRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  ComponentsTypographyRoute: typeof ComponentsTypographyRoute
  GettingStartedCustomizationRoute: typeof GettingStartedCustomizationRoute
  GettingStartedInstallationRoute: typeof GettingStartedInstallationRoute
  GettingStartedUsageRoute: typeof GettingStartedUsageRoute
  TokensColorsRoute: typeof TokensColorsRoute
  TokensMiscRoute: typeof TokensMiscRoute
  TokensSpacingRoute: typeof TokensSpacingRoute
  TokensTypographyRoute: typeof TokensTypographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/typography': {
      id: '/tokens/typography'
      path: '/tokens/typography'
      fullPath: '/tokens/typography'
      preLoaderRoute: typeof TokensTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/spacing': {
      id: '/tokens/spacing'
      path: '/tokens/spacing'
      fullPath: '/tokens/spacing'
      preLoaderRoute: typeof TokensSpacingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/misc': {
      id: '/tokens/misc'
      path: '/tokens/misc'
      fullPath: '/tokens/misc'
      preLoaderRoute: typeof TokensMiscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/colors': {
      id: '/tokens/colors'
      path: '/tokens/colors'
      fullPath: '/tokens/colors'
      preLoaderRoute: typeof TokensColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started/usage': {
      id: '/getting-started/usage'
      path: '/getting-started/usage'
      fullPath: '/getting-started/usage'
      preLoaderRoute: typeof GettingStartedUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started/installation': {
      id: '/getting-started/installation'
      path: '/getting-started/installation'
      fullPath: '/getting-started/installation'
      preLoaderRoute: typeof GettingStartedInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started/customization': {
      id: '/getting-started/customization'
      path: '/getting-started/customization'
      fullPath: '/getting-started/customization'
      preLoaderRoute: typeof GettingStartedCustomizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/typography': {
      id: '/components/typography'
      path: '/components/typography'
      fullPath: '/components/typography'
      preLoaderRoute: typeof ComponentsTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/components/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/text-field': {
      id: '/components/text-field'
      path: '/components/text-field'
      fullPath: '/components/text-field'
      preLoaderRoute: typeof ComponentsTextFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/components/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/table': {
      id: '/components/table'
      path: '/components/table'
      fullPath: '/components/table'
      preLoaderRoute: typeof ComponentsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/components/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/stack': {
      id: '/components/stack'
      path: '/components/stack'
      fullPath: '/components/stack'
      preLoaderRoute: typeof ComponentsStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/snackbar': {
      id: '/components/snackbar'
      path: '/components/snackbar'
      fullPath: '/components/snackbar'
      preLoaderRoute: typeof ComponentsSnackbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/slider': {
      id: '/components/slider'
      path: '/components/slider'
      fullPath: '/components/slider'
      preLoaderRoute: typeof ComponentsSliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/components/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/sidebar-component': {
      id: '/components/sidebar-component'
      path: '/components/sidebar-component'
      fullPath: '/components/sidebar-component'
      preLoaderRoute: typeof ComponentsSidebarComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/search-bar': {
      id: '/components/search-bar'
      path: '/components/search-bar'
      fullPath: '/components/search-bar'
      preLoaderRoute: typeof ComponentsSearchBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/radio': {
      id: '/components/radio'
      path: '/components/radio'
      fullPath: '/components/radio'
      preLoaderRoute: typeof ComponentsRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/pagination': {
      id: '/components/pagination'
      path: '/components/pagination'
      fullPath: '/components/pagination'
      preLoaderRoute: typeof ComponentsPaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/navbar-component': {
      id: '/components/navbar-component'
      path: '/components/navbar-component'
      fullPath: '/components/navbar-component'
      preLoaderRoute: typeof ComponentsNavbarComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/menu': {
      id: '/components/menu'
      path: '/components/menu'
      fullPath: '/components/menu'
      preLoaderRoute: typeof ComponentsMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/list': {
      id: '/components/list'
      path: '/components/list'
      fullPath: '/components/list'
      preLoaderRoute: typeof ComponentsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/linear-progress': {
      id: '/components/linear-progress'
      path: '/components/linear-progress'
      fullPath: '/components/linear-progress'
      preLoaderRoute: typeof ComponentsLinearProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input': {
      id: '/components/input'
      path: '/components/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/icon': {
      id: '/components/icon'
      path: '/components/icon'
      fullPath: '/components/icon'
      preLoaderRoute: typeof ComponentsIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/form-field': {
      id: '/components/form-field'
      path: '/components/form-field'
      fullPath: '/components/form-field'
      preLoaderRoute: typeof ComponentsFormFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/drawer': {
      id: '/components/drawer'
      path: '/components/drawer'
      fullPath: '/components/drawer'
      preLoaderRoute: typeof ComponentsDrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/divider': {
      id: '/components/divider'
      path: '/components/divider'
      fullPath: '/components/divider'
      preLoaderRoute: typeof ComponentsDividerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dialog': {
      id: '/components/dialog'
      path: '/components/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/date-picker': {
      id: '/components/date-picker'
      path: '/components/date-picker'
      fullPath: '/components/date-picker'
      preLoaderRoute: typeof ComponentsDatePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/data-table': {
      id: '/components/data-table'
      path: '/components/data-table'
      fullPath: '/components/data-table'
      preLoaderRoute: typeof ComponentsDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/circular-progress': {
      id: '/components/circular-progress'
      path: '/components/circular-progress'
      fullPath: '/components/circular-progress'
      preLoaderRoute: typeof ComponentsCircularProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/chip': {
      id: '/components/chip'
      path: '/components/chip'
      fullPath: '/components/chip'
      preLoaderRoute: typeof ComponentsChipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/card': {
      id: '/components/card'
      path: '/components/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/breadcrumbs': {
      id: '/components/breadcrumbs'
      path: '/components/breadcrumbs'
      fullPath: '/components/breadcrumbs'
      preLoaderRoute: typeof ComponentsBreadcrumbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/box': {
      id: '/components/box'
      path: '/components/box'
      fullPath: '/components/box'
      preLoaderRoute: typeof ComponentsBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/components/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/avatar': {
      id: '/components/avatar'
      path: '/components/avatar'
      fullPath: '/components/avatar'
      preLoaderRoute: typeof ComponentsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/autocomplete': {
      id: '/components/autocomplete'
      path: '/components/autocomplete'
      fullPath: '/components/autocomplete'
      preLoaderRoute: typeof ComponentsAutocompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/alert': {
      id: '/components/alert'
      path: '/components/alert'
      fullPath: '/components/alert'
      preLoaderRoute: typeof ComponentsAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/accordion': {
      id: '/components/accordion'
      path: '/components/accordion'
      fullPath: '/components/accordion'
      preLoaderRoute: typeof ComponentsAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsAccordionRoute: ComponentsAccordionRoute,
  ComponentsAlertRoute: ComponentsAlertRoute,
  ComponentsAutocompleteRoute: ComponentsAutocompleteRoute,
  ComponentsAvatarRoute: ComponentsAvatarRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsBoxRoute: ComponentsBoxRoute,
  ComponentsBreadcrumbsRoute: ComponentsBreadcrumbsRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCardRoute: ComponentsCardRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsChipRoute: ComponentsChipRoute,
  ComponentsCircularProgressRoute: ComponentsCircularProgressRoute,
  ComponentsDataTableRoute: ComponentsDataTableRoute,
  ComponentsDatePickerRoute: ComponentsDatePickerRoute,
  ComponentsDialogRoute: ComponentsDialogRoute,
  ComponentsDividerRoute: ComponentsDividerRoute,
  ComponentsDrawerRoute: ComponentsDrawerRoute,
  ComponentsFormFieldRoute: ComponentsFormFieldRoute,
  ComponentsIconRoute: ComponentsIconRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsLinearProgressRoute: ComponentsLinearProgressRoute,
  ComponentsListRoute: ComponentsListRoute,
  ComponentsMenuRoute: ComponentsMenuRoute,
  ComponentsNavbarComponentRoute: ComponentsNavbarComponentRoute,
  ComponentsPaginationRoute: ComponentsPaginationRoute,
  ComponentsRadioRoute: ComponentsRadioRoute,
  ComponentsSearchBarRoute: ComponentsSearchBarRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSidebarComponentRoute: ComponentsSidebarComponentRoute,
  ComponentsSkeletonRoute: ComponentsSkeletonRoute,
  ComponentsSliderRoute: ComponentsSliderRoute,
  ComponentsSnackbarRoute: ComponentsSnackbarRoute,
  ComponentsStackRoute: ComponentsStackRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTableRoute: ComponentsTableRoute,
  ComponentsTabsRoute: ComponentsTabsRoute,
  ComponentsTextFieldRoute: ComponentsTextFieldRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  ComponentsTypographyRoute: ComponentsTypographyRoute,
  GettingStartedCustomizationRoute: GettingStartedCustomizationRoute,
  GettingStartedInstallationRoute: GettingStartedInstallationRoute,
  GettingStartedUsageRoute: GettingStartedUsageRoute,
  TokensColorsRoute: TokensColorsRoute,
  TokensMiscRoute: TokensMiscRoute,
  TokensSpacingRoute: TokensSpacingRoute,
  TokensTypographyRoute: TokensTypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
