/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClaudeMdRouteImport } from './routes/claude-md'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokensTypographyRouteImport } from './routes/tokens/typography'
import { Route as TokensSpacingRouteImport } from './routes/tokens/spacing'
import { Route as TokensMiscRouteImport } from './routes/tokens/misc'
import { Route as TokensColorsRouteImport } from './routes/tokens/colors'
import { Route as ComponentsTypographyRouteImport } from './routes/components/typography'
import { Route as ComponentsTooltipRouteImport } from './routes/components/tooltip'
import { Route as ComponentsTextFieldRouteImport } from './routes/components/text-field'
import { Route as ComponentsSwitchRouteImport } from './routes/components/switch'
import { Route as ComponentsStackRouteImport } from './routes/components/stack'
import { Route as ComponentsSliderRouteImport } from './routes/components/slider'
import { Route as ComponentsSkeletonRouteImport } from './routes/components/skeleton'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsRadioRouteImport } from './routes/components/radio'
import { Route as ComponentsLinearProgressRouteImport } from './routes/components/linear-progress'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsIconRouteImport } from './routes/components/icon'
import { Route as ComponentsDividerRouteImport } from './routes/components/divider'
import { Route as ComponentsCircularProgressRouteImport } from './routes/components/circular-progress'
import { Route as ComponentsChipRouteImport } from './routes/components/chip'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsBoxRouteImport } from './routes/components/box'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'
import { Route as ComponentsAvatarRouteImport } from './routes/components/avatar'
import { Route as ComponentsAlertRouteImport } from './routes/components/alert'

const ClaudeMdRoute = ClaudeMdRouteImport.update({
  id: '/claude-md',
  path: '/claude-md',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensTypographyRoute = TokensTypographyRouteImport.update({
  id: '/tokens/typography',
  path: '/tokens/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensSpacingRoute = TokensSpacingRouteImport.update({
  id: '/tokens/spacing',
  path: '/tokens/spacing',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensMiscRoute = TokensMiscRouteImport.update({
  id: '/tokens/misc',
  path: '/tokens/misc',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensColorsRoute = TokensColorsRouteImport.update({
  id: '/tokens/colors',
  path: '/tokens/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTypographyRoute = ComponentsTypographyRouteImport.update({
  id: '/components/typography',
  path: '/components/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/components/tooltip',
  path: '/components/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextFieldRoute = ComponentsTextFieldRouteImport.update({
  id: '/components/text-field',
  path: '/components/text-field',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/components/switch',
  path: '/components/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsStackRoute = ComponentsStackRouteImport.update({
  id: '/components/stack',
  path: '/components/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSliderRoute = ComponentsSliderRouteImport.update({
  id: '/components/slider',
  path: '/components/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSkeletonRoute = ComponentsSkeletonRouteImport.update({
  id: '/components/skeleton',
  path: '/components/skeleton',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRadioRoute = ComponentsRadioRouteImport.update({
  id: '/components/radio',
  path: '/components/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsLinearProgressRoute =
  ComponentsLinearProgressRouteImport.update({
    id: '/components/linear-progress',
    path: '/components/linear-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/components/input',
  path: '/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIconRoute = ComponentsIconRouteImport.update({
  id: '/components/icon',
  path: '/components/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDividerRoute = ComponentsDividerRouteImport.update({
  id: '/components/divider',
  path: '/components/divider',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCircularProgressRoute =
  ComponentsCircularProgressRouteImport.update({
    id: '/components/circular-progress',
    path: '/components/circular-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsChipRoute = ComponentsChipRouteImport.update({
  id: '/components/chip',
  path: '/components/chip',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBoxRoute = ComponentsBoxRouteImport.update({
  id: '/components/box',
  path: '/components/box',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAvatarRoute = ComponentsAvatarRouteImport.update({
  id: '/components/avatar',
  path: '/components/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAlertRoute = ComponentsAlertRouteImport.update({
  id: '/components/alert',
  path: '/components/alert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claude-md': typeof ClaudeMdRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/box': typeof ComponentsBoxRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/chip': typeof ComponentsChipRoute
  '/components/circular-progress': typeof ComponentsCircularProgressRoute
  '/components/divider': typeof ComponentsDividerRoute
  '/components/icon': typeof ComponentsIconRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/linear-progress': typeof ComponentsLinearProgressRoute
  '/components/radio': typeof ComponentsRadioRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/text-field': typeof ComponentsTextFieldRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/typography': typeof ComponentsTypographyRoute
  '/tokens/colors': typeof TokensColorsRoute
  '/tokens/misc': typeof TokensMiscRoute
  '/tokens/spacing': typeof TokensSpacingRoute
  '/tokens/typography': typeof TokensTypographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claude-md': typeof ClaudeMdRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/box': typeof ComponentsBoxRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/chip': typeof ComponentsChipRoute
  '/components/circular-progress': typeof ComponentsCircularProgressRoute
  '/components/divider': typeof ComponentsDividerRoute
  '/components/icon': typeof ComponentsIconRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/linear-progress': typeof ComponentsLinearProgressRoute
  '/components/radio': typeof ComponentsRadioRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/text-field': typeof ComponentsTextFieldRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/typography': typeof ComponentsTypographyRoute
  '/tokens/colors': typeof TokensColorsRoute
  '/tokens/misc': typeof TokensMiscRoute
  '/tokens/spacing': typeof TokensSpacingRoute
  '/tokens/typography': typeof TokensTypographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claude-md': typeof ClaudeMdRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/box': typeof ComponentsBoxRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/chip': typeof ComponentsChipRoute
  '/components/circular-progress': typeof ComponentsCircularProgressRoute
  '/components/divider': typeof ComponentsDividerRoute
  '/components/icon': typeof ComponentsIconRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/linear-progress': typeof ComponentsLinearProgressRoute
  '/components/radio': typeof ComponentsRadioRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/stack': typeof ComponentsStackRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/text-field': typeof ComponentsTextFieldRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/components/typography': typeof ComponentsTypographyRoute
  '/tokens/colors': typeof TokensColorsRoute
  '/tokens/misc': typeof TokensMiscRoute
  '/tokens/spacing': typeof TokensSpacingRoute
  '/tokens/typography': typeof TokensTypographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claude-md'
    | '/components/alert'
    | '/components/avatar'
    | '/components/badge'
    | '/components/box'
    | '/components/button'
    | '/components/checkbox'
    | '/components/chip'
    | '/components/circular-progress'
    | '/components/divider'
    | '/components/icon'
    | '/components/input'
    | '/components/linear-progress'
    | '/components/radio'
    | '/components/select'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/stack'
    | '/components/switch'
    | '/components/text-field'
    | '/components/tooltip'
    | '/components/typography'
    | '/tokens/colors'
    | '/tokens/misc'
    | '/tokens/spacing'
    | '/tokens/typography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claude-md'
    | '/components/alert'
    | '/components/avatar'
    | '/components/badge'
    | '/components/box'
    | '/components/button'
    | '/components/checkbox'
    | '/components/chip'
    | '/components/circular-progress'
    | '/components/divider'
    | '/components/icon'
    | '/components/input'
    | '/components/linear-progress'
    | '/components/radio'
    | '/components/select'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/stack'
    | '/components/switch'
    | '/components/text-field'
    | '/components/tooltip'
    | '/components/typography'
    | '/tokens/colors'
    | '/tokens/misc'
    | '/tokens/spacing'
    | '/tokens/typography'
  id:
    | '__root__'
    | '/'
    | '/claude-md'
    | '/components/alert'
    | '/components/avatar'
    | '/components/badge'
    | '/components/box'
    | '/components/button'
    | '/components/checkbox'
    | '/components/chip'
    | '/components/circular-progress'
    | '/components/divider'
    | '/components/icon'
    | '/components/input'
    | '/components/linear-progress'
    | '/components/radio'
    | '/components/select'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/stack'
    | '/components/switch'
    | '/components/text-field'
    | '/components/tooltip'
    | '/components/typography'
    | '/tokens/colors'
    | '/tokens/misc'
    | '/tokens/spacing'
    | '/tokens/typography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaudeMdRoute: typeof ClaudeMdRoute
  ComponentsAlertRoute: typeof ComponentsAlertRoute
  ComponentsAvatarRoute: typeof ComponentsAvatarRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsBoxRoute: typeof ComponentsBoxRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsChipRoute: typeof ComponentsChipRoute
  ComponentsCircularProgressRoute: typeof ComponentsCircularProgressRoute
  ComponentsDividerRoute: typeof ComponentsDividerRoute
  ComponentsIconRoute: typeof ComponentsIconRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsLinearProgressRoute: typeof ComponentsLinearProgressRoute
  ComponentsRadioRoute: typeof ComponentsRadioRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSkeletonRoute: typeof ComponentsSkeletonRoute
  ComponentsSliderRoute: typeof ComponentsSliderRoute
  ComponentsStackRoute: typeof ComponentsStackRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTextFieldRoute: typeof ComponentsTextFieldRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  ComponentsTypographyRoute: typeof ComponentsTypographyRoute
  TokensColorsRoute: typeof TokensColorsRoute
  TokensMiscRoute: typeof TokensMiscRoute
  TokensSpacingRoute: typeof TokensSpacingRoute
  TokensTypographyRoute: typeof TokensTypographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/claude-md': {
      id: '/claude-md'
      path: '/claude-md'
      fullPath: '/claude-md'
      preLoaderRoute: typeof ClaudeMdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/typography': {
      id: '/tokens/typography'
      path: '/tokens/typography'
      fullPath: '/tokens/typography'
      preLoaderRoute: typeof TokensTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/spacing': {
      id: '/tokens/spacing'
      path: '/tokens/spacing'
      fullPath: '/tokens/spacing'
      preLoaderRoute: typeof TokensSpacingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/misc': {
      id: '/tokens/misc'
      path: '/tokens/misc'
      fullPath: '/tokens/misc'
      preLoaderRoute: typeof TokensMiscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/colors': {
      id: '/tokens/colors'
      path: '/tokens/colors'
      fullPath: '/tokens/colors'
      preLoaderRoute: typeof TokensColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/typography': {
      id: '/components/typography'
      path: '/components/typography'
      fullPath: '/components/typography'
      preLoaderRoute: typeof ComponentsTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/components/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/text-field': {
      id: '/components/text-field'
      path: '/components/text-field'
      fullPath: '/components/text-field'
      preLoaderRoute: typeof ComponentsTextFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/components/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/stack': {
      id: '/components/stack'
      path: '/components/stack'
      fullPath: '/components/stack'
      preLoaderRoute: typeof ComponentsStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/slider': {
      id: '/components/slider'
      path: '/components/slider'
      fullPath: '/components/slider'
      preLoaderRoute: typeof ComponentsSliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/components/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/radio': {
      id: '/components/radio'
      path: '/components/radio'
      fullPath: '/components/radio'
      preLoaderRoute: typeof ComponentsRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/linear-progress': {
      id: '/components/linear-progress'
      path: '/components/linear-progress'
      fullPath: '/components/linear-progress'
      preLoaderRoute: typeof ComponentsLinearProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input': {
      id: '/components/input'
      path: '/components/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/icon': {
      id: '/components/icon'
      path: '/components/icon'
      fullPath: '/components/icon'
      preLoaderRoute: typeof ComponentsIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/divider': {
      id: '/components/divider'
      path: '/components/divider'
      fullPath: '/components/divider'
      preLoaderRoute: typeof ComponentsDividerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/circular-progress': {
      id: '/components/circular-progress'
      path: '/components/circular-progress'
      fullPath: '/components/circular-progress'
      preLoaderRoute: typeof ComponentsCircularProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/chip': {
      id: '/components/chip'
      path: '/components/chip'
      fullPath: '/components/chip'
      preLoaderRoute: typeof ComponentsChipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/box': {
      id: '/components/box'
      path: '/components/box'
      fullPath: '/components/box'
      preLoaderRoute: typeof ComponentsBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/components/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/avatar': {
      id: '/components/avatar'
      path: '/components/avatar'
      fullPath: '/components/avatar'
      preLoaderRoute: typeof ComponentsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/alert': {
      id: '/components/alert'
      path: '/components/alert'
      fullPath: '/components/alert'
      preLoaderRoute: typeof ComponentsAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaudeMdRoute: ClaudeMdRoute,
  ComponentsAlertRoute: ComponentsAlertRoute,
  ComponentsAvatarRoute: ComponentsAvatarRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsBoxRoute: ComponentsBoxRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsChipRoute: ComponentsChipRoute,
  ComponentsCircularProgressRoute: ComponentsCircularProgressRoute,
  ComponentsDividerRoute: ComponentsDividerRoute,
  ComponentsIconRoute: ComponentsIconRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsLinearProgressRoute: ComponentsLinearProgressRoute,
  ComponentsRadioRoute: ComponentsRadioRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSkeletonRoute: ComponentsSkeletonRoute,
  ComponentsSliderRoute: ComponentsSliderRoute,
  ComponentsStackRoute: ComponentsStackRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTextFieldRoute: ComponentsTextFieldRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  ComponentsTypographyRoute: ComponentsTypographyRoute,
  TokensColorsRoute: TokensColorsRoute,
  TokensMiscRoute: TokensMiscRoute,
  TokensSpacingRoute: TokensSpacingRoute,
  TokensTypographyRoute: TokensTypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
